### ISSUE TITLE
Allow setting default system proxy for netcoreapp2.1

### ISSUE THREAD

**Issue by Priya91** [Azure/azure-relay-dotnet#104]
Today, for netcoreapp2.1 flavor of the library, it is not possible to let the .NET Core implementation use the system proxy settings by default.

.NET Core uses the system proxy settings, only if the user doesn't set any proxy value on ClientWebSocketOptions.Proxy property. The relay lib always sets this property to some value, either WebRequest.DefaultWebProxy (which is deprecated for .netcore) or the user provided value.

If the user does not set the proxy value on the api, then the HybridConnectionClient or the HybridConnectionListener should not set the proxy value on the ClientWebSocketOptions.Proxy.

**Comment by dlstucki** [comment]
The code to always set something on ClientWebSocketOptions.Proxy was to fix a separate issue. There was an unhandled exception on a worker thread when this didn't occur. ClientWebSocket.Abort was throwing some weird exception in that case. I can dig up those details if that helps in any way.

**Comment by dlstucki** [comment]
Is this when UseBuiltInClientWebSocket is true or false?

**Comment by Priya91** [comment]
UseBuiltInClientWebSocket = true, when using the .NET Core ClientWebSocket

**Comment by dlstucki** [comment]
What would you like to have happen if the user sets HybridConnectionListener.Proxy = null? Should we explicitly set ClientWebSocketOptions.Proxy to null or not touch it?

**Comment by Priya91** [comment]
If the user sets it to null, the ClientWebSocketOptions.Proxy should be set to null. That's the same behavior for ClientWebSocketOptions as well, basically just mimic what .NET Core is doing.

**Comment by dlstucki** [comment]
This is the current behavior:

Platform|UseBuildInCWS|ProxyConfig|ProxyUsed|IsCorrect
---------|-----------------|-------------|------------|----------
net46    | N/A                 | SystemDefault |Yes | :heavy_check_mark: Yes
net46    | N/A                 | ExplicitlySet| Yes | :heavy_check_mark: Yes
net46    | N/A                 | ExplicitNull  | No | :heavy_check_mark: Yes
---------|-----------------|-------------|------------|----------
netcoreapp2.0 | false          | SystemDefault | No  | :x: **No**
netcoreapp2.0 | false          | ExplicitNull | No | :heavy_check_mark: Yes
netcoreapp2.0 | false          | ExplicitlySet | Yes | :heavy_check_mark: Yes
netcoreapp2.0 | true           | SystemDefault  | No | :x: **No**
netcoreapp2.0 | true           | ExplicitNull  | No | :heavy_check_mark: Yes
netcoreapp2.0 | true           | ExplicitlySet     | No |  :x: **No**
---------|-----------------|-------------|------------|----------
netcoreapp2.1 | false          | SystemDefault       | No |  :x: **No**
netcoreapp2.1 | false          | ExplicitNull   | No | :heavy_check_mark: Yes
netcoreapp2.1 | false          | ExplicitlySet| Yes | :heavy_check_mark: Yes
netcoreapp2.1 | true           | SystemDefault      | No |  :x: **No**
netcoreapp2.1 | true           | ExplicitNull  | No | :heavy_check_mark: Yes
netcoreapp2.1 | true           | ExplicitlySet   | Yes | :heavy_check_mark: Yes

**Comment by dlstucki** [comment]
PR is merged. Will be in next release.
