### ISSUE TITLE
Query parameter encoding is not what I would expect

### ISSUE THREAD

**Issue by Casper-Olsen** [Azure/azure-relay-dotnet#151]
When adding query parameters to a call that is relayed, the query parameters received at the listener is not what I would expect.
 This is when using characters such as `æ`, `ø`,`å`.
 
I have tried debugging through the code in the Microsoft.Azure.Relay package and i haven't been able to find out what causes this. 

## Actual Behavior 
`ø` = `%C3%B8` when URL encoded

 Examples of calling the relay:
 `https://my-relay.servicebus.windows.net/my-relay/foo/test?name=%C3%B8` (with URL encoding)
 `https://my-relay.servicebus.windows.net/my-relay/foo/test?name=ø` (without URL encoding)  

Both of these calls lead to the same query parameter encoding in the listener (`RelayedHttpListenerContext`):
`/my-relay/foo/test?name=%u00f8` (OriginalString)
`/my-relay/foo/test?name=%25u00f8` (AbsoluteUri)

So `ø`/`%C3%B8` -> `%u00f8`  

<br>

It looks like the parameter has been encoded with UTF-16 in the OriginalString and in the AbsoluteUri the `%` part has been URL-encoded together with the original UTF-16 encoding.

## Expected Behavior
I would expect the same encoding as I used in the request: `%C3%B8`

Is the encoding i receive in the listener what you would expect?
If yes: Is there a way to override the behavior? Or do i need to handle the URL-Encoding + UTF-16 encoding in the listener code?

## Versions  
- OS platform and version: Windows 10
- .NET Version: .NET Core 3.1
- NuGet package version or commit ID: Microsoft.Azure.Relay 2.0.1

**Comment by dlstucki** [comment]
I have confirmed this is strange behavior emanating from the cloud service. This code shows a similar set of steps which results in output like you are seeing.

``` csharp
    void TestUrl(string testUrl)
    {
        var uri = new Uri(testUrl);
        NameValueCollection queryStringCollection = System.Web.HttpUtility.ParseQueryString(uri.Query);
        string newQuery = queryStringCollection.ToString();

        Console.WriteLine($"OriginalUrl:    {testUrl}");
        Console.WriteLine($"Re-Serialized:  {newQuery}");
    }

    string s1 = "https://my-relay.servicebus.windows.net/my-relay/foo/test?name=%C3%B8"; // (with URL encoding)
    string s2 = "https://my-relay.servicebus.windows.net/my-relay/foo/test?name=ø"; // (without URL encoding)

    TestUrl(s1);
    TestUrl(s2);
```

To avoid this occurring will require cloud service changes which I'll add to the backlog.

**Comment by Casper-Olsen** [comment]
@dlstucki Appreciate it :)

Is the backlog public?

**Comment by dlstucki** [comment]
This fix is now in the repo for the cloud service itself. Also made corresponding #152 here though it's not required to get the fixed behavior. The next time the cloud service is updated (eta 1 month or less) this will start working properly.

**Comment by Casper-Olsen** [comment]
@dlstucki Thank you :)

**Comment by dlstucki** [comment]
Reopen if you still encounter the issue.
