### ISSUE TITLE
The Runtime unit tests hang when run as a group...

### ISSUE THREAD

**Issue by dstuckims** [Azure/azure-relay-dotnet#23]
This is due to some of the tests not closing their HybridConnectionListeners.  The tests Write1Mb, ListenerShutdown, ListenerAbortWhileClientReading all fail to close their listener resulting in tests run after them sometime connecting the wrong listener.

I recommend putting a try/finally block around any test that opens a listener so even in the case of that test throwing an exception other tests using the same HC don't encounter a rogue listener.

We may want to consider whether HybridConnectionListener class should actually implement IDisposable to allow "using { }" blocks in cases like this.

**Comment by jtaubensee** [comment]
Solved with #26
