### ISSUE TITLE
"simple" sample build

### ISSUE THREAD

**Issue by pmhsfelix** [Azure/azure-relay-dotnet#31]
The "simple" sample .csproj (both client and server) are referencing DLLs located at `..\..\..\..\..\temp\SBRelay\Microsoft.Azure.Relay.dll`. How are those DLLs supposed to get there? 
* Is there anything that must be build before?
* Shouldn't these DLLs be provided via nuget instead?

**Comment by jtaubensee** [comment]
@pmhsfelix - Thanks for catching this. We are actually going to move these samples to new repos in the Azure-Samples org. Stay tuned for the new locations (in the next day or two). I will also make sure they use the NuGet packages.

**Comment by pmhsfelix** [comment]
Ok, thanks. I'll wait for that.

**Comment by jtaubensee** [comment]
The samples are actually going to stay where they are for a little while, but hopefully we will move them early next year.
