### ISSUE TITLE
Once Listener Accept commands use DNS instead of Direct IP remove the clone(s?) of ClientWebSocket

### ISSUE THREAD

**Issue by dstuckims** [Azure/azure-relay-dotnet#34]
Up to this point we had to clone the ClientWebSocket class because the built-in version(s) didn't allow us to rendezvous (when the listener accepts a sender) using an IP address.  The SSL negotiation would fail because the Server's Certificate Subject was "*.servicebus.windows.net" and didn't match the IP Address.  

Sometime in December an update is rolling out which changes ServiceBus/AzureRelay cloud gateway machines to register DNS records like "g0-prod-sn1-001-sb.servicebus.windows.net" and changes HybridConnection Listener Accept commands to use these new DNS names.   Once that update is deployed worldwide we could remove the clone of ClientWebSocket (at least from the .NET 4.5 target).

**Comment by jtaubensee** [comment]
@dstuckims - This can be removed now, correct?

**Comment by dstuckims** [comment]
@jtaubensee , that is correct, but we need to decide what to do as far as ClientWebSocket overall.

1. Should we use the built in ClientWebSocket for .NET 4.5?
2. Should we use the built in ClientWebSocket for .NET Core (which has known issues and probably issues we're not even aware of).
3. Keep one or both of the above clones we already have?
4. Should we "port" and use the ServiceBusClientWebSocket class from Microsoft.ServiceBus.dll.  This is SB team's own custom implementation of websocket client, with proxy support (NTLM proxy auth uses Win32 APIs though and would likely need to be if-def'd out for .NET Core).

**Comment by jtaubensee** [comment]
My thought would be to start using the ClientWebSocket for .NET 4.5 (assuming all the features are there), and continue using the custom implementation for .NET Core, with the intention of removing it once the outstanding features/bugs we have with their team are addressed.

https://github.com/dotnet/corefx/issues/14103
https://github.com/dotnet/corefx/issues/13773

**Comment by jtaubensee** [comment]
@dstuckims - Can this be closed now?

**Comment by dstuckims** [comment]
Yes.
