### ISSUE TITLE
UWP not supported due to Thread and ThreadPool

### ISSUE THREAD

**Issue by onovotny** [Azure/azure-relay-dotnet#36]
Similar to https://github.com/Azure/azure-service-bus-dotnet/issues/50 , `Thread` and `ThreadPool` are not supported on UWP. I wish they were and might eventually be eventually. For now, can you please cross-compile to a UAP10.0 version or use `Task`.

See https://github.com/dotnet/corefx/issues/2576 for the issue tracking Thread/ThreadPool in UWP.

/cc @terrajobst

**Comment by dstuckims** [comment]
Sounds like a good update to make.  I just did a quick search and I didn't find more than a few uses in the main assembly.

**Comment by jtaubensee** [comment]
@dstuckims - I'm pretty sure that Task.Run will work, and can help with the specifics of "cross-compile to a UAP10.0 version"

**Comment by dstuckims** [comment]
Getting rid of Thread and ThreadPool references is pretty straightforward (See: https://github.com/dstuckims/azure-relay-dotnet/tree/NoMoreThreadOrThreadPool).  What isn't simple is how we take our code which uses the System.Net.WebSockets.WebSocket and ClientWebSocket classes into UWP land.  @onovotny if you have any suggestions here that would help me out.

**Comment by onovotny** [comment]
Are you sure ClientWebSocket doesn't work with UWP? Looking at the package `System.Net.WebSockets.Client`, it has a `netstandard1.3` ref assembly and a `\runtimes\win\lib\netcore50` impl, so that seems like it'd support UWP? I have not tested it though.

**Comment by onovotny** [comment]
I just created a new UWP app in VS 2015 and was able to add `System.Net.WebSockets.Client` and see the `ClientWebSocket` type. 

BTW, I would recommend using `NETStandard.Library` 1.6.1 and not 1.6.0 in all of your libraries because 1.6.0 has issues installing into Xamarin Studio that were fixed by 1.6.1.

**Comment by dstuckims** [comment]
Ok, do you like this better: https://github.com/dstuckims/azure-relay-dotnet/commit/3b86665ab3dfe968af48e705a37300a92ec84246 ?  

Up until a service upgrade that finally finished today this code had to have its own copies of ClientWebSocket in order to get SSL to work since the listener's "accept" websocket connection had to use an IP address (which, of course, didn't match the SSL Certificate Subject: *.servicebus.windows.net).

**Comment by onovotny** [comment]
@dstuckims I'm not sure I'm following the commit above; I don't think you need an explicit UWP project. That would seem to give you more maintanance work :)

The netstandard1.3 version should work on UWP as-is once thread and threadpool were removed. Most .NET Standard-based libraries will work on UWP but Thread/ThreadPool are current gaps.

Easiest way to test is to create a UWP test application and reference your project/NuPkg to verify expected functionality. Also, putting your unit tests into a shared code project and then using them in desktop, netcoreapp, and UWP test projects is a good way to verify expected functionality across runtimes. If you're feeling adventurous, there's a device runner for Xamarin iOS/Android if you want to explicitly verify the tests there too.

**Comment by dstuckims** [comment]
Do you think this commit would be sufficient? (https://github.com/dstuckims/azure-relay-dotnet/commit/93777a9f8563bbdacc4b854afd9fb21a968196b9)

**Comment by dstuckims** [comment]
@onovotny Is there any way you could verify this or do you need to wait until a Nuget package is published with these changes?

**Comment by onovotny** [comment]
Sorry, it's been a busy week. The easiest way to verify is to create a UWP test harness project and add a reference. P2P and a NuGet ref *should* be the same, but it never hurts to try both. I probably won't have time to do this before Monday, at the earliest.

**Comment by jtaubensee** [comment]
Check out #42

**Comment by dlstucki** [comment]
Can this issue be closed now? Neither Thread nor ThreadPool are used in this project any more.

**Comment by dlstucki** [comment]
Closing due to no clear further action and no response for a month. Please reactivate if necessary.
