### ISSUE TITLE
Test project is missing?

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-relay-dotnet#4]
[`global.json`](https://github.com/Azure/azure-relay-dotnet/blob/b280332b0e15ecbc8a72d32df37023e4678c0296/global.json#L2) indicates there should be a test project, though it's missing from the tree.

**Comment by jtaubensee** [comment]
Tests will be coming... We have internal tests that will create/delete namespaces using the ServiceBus.dll. We will be modifying them to run similar to the Event Hubs tests (/azure/azure-event-hubs-dotnet).

**Comment by jtaubensee** [comment]
Added unit tests with #18

**Comment by jtaubensee** [comment]
Will need to update the readme to give directions on running the ARM templates

**Comment by jtaubensee** [comment]
Added directions #19
