### ISSUE TITLE
Update the dotnet clientwebsocket implementation

### ISSUE THREAD

**Issue by Priya91** [Azure/azure-relay-dotnet#61]
Dotnet clientwebsocket implementation has changed, and a new apis have been released. So change the implementation to just consume the dotnetcore ClientWebSocket, instead of duplicating the source and building here. The repo there now provides support for Proxies which is missing in the current source code.

**Comment by wokket** [comment]
I second this... I need support for outbound proxy support in a government arena, it's taken me a good couple of hours of trial and error and code reading to discover that the proxy support in here is apparently non-functional...

**Comment by dlstucki** [comment]
PR https://github.com/Azure/azure-relay-dotnet/pull/73 introduced a flag to control this. Starting with [2.0.0-preview1-20180523](https://github.com/Azure/azure-relay-dotnet/releases/tag/2.0.0-preview1-20180523) there is a `UseBuiltInClientWebSocket` property on `HybridConnectionClient` and `HybridConnectionListener`. At this time the default is false but that may change in the future when the build-in ClientWebSocket implementation is the preferable one in all cases.

**Comment by Priya91** [comment]
@dlstucki Any update on this? It would be great if the custom websocket implementation in the repo got an update from .netcore, then we will get all the features as well the diagnostic information support

**Comment by dlstucki** [comment]
If we change the Microsoft.Azure.Relay library to use built in ClientWebSocket by default wouldn't it potentially break existing users if they update the Relay package don't update to a newer version of netcoreapp? I can't say I'm completely aware of the versioning and back-compat best practices in this new world.

**Comment by dlstucki** [comment]
Addressed by PR #109

**Comment by dlstucki** [comment]
Fixed in [release 2.0.1](https://github.com/Azure/azure-relay-dotnet/releases/tag/2.0.1)
