### ISSUE TITLE
Expose trackingContext for external correlation

### ISSUE THREAD

**Issue by ltrain777** [Azure/azure-relay-dotnet#65]
We would like to propose making the TrackingContext property public (getter) instead of internal.

We are using the AcceptHandler to parse the Request queryString (for custom validation and to get configuration) and store the values in a dictionary. Currently we ToString() the RelayedHttpListenerContext to get the TrackingId from regex in the AcceptHandler, after it successfully returns true from the AcceptHandler, we ToString() the HybridConnectionStream to get the TrackingId again to correlate.

This seems error prone and could break due to name changes.  Is there a reason why the TrackingContext is internal only?

We can have a PR for this if there are no objections to exposing the TrackingContext.

**Comment by ltrain777** [comment]
We just want the TrackingId and ActivityId, but the SubsystemId would be nice for tracing.

**Comment by dlstucki** [comment]
Are you suggesting just adding the two string properties on the ListenerContext and Stream classes? I'm actually leaning more towards making TrackingContext and the getters public.

**Comment by dlstucki** [comment]
Also, can you help me think of any better name for `TrackingContext.SubsystemId`? This entire TrackingContext concept came from Microsoft.ServiceBus.dll's `TrackingContext`. There it's called `SystemTracker` and I always disliked that name. It's a context specific representation of some address which makes sense for whatever subsystem it's in. It's usually something like `contoso.servicebus.windows.net/hybridconnection1` but, at least in service bus, it will also change, sometimes looking like `contoso:Queue:my_queue`, other times simply looking like `SuperAwesomeCloudServiceComponent` when there's no user specific info (like a background timer which isn't directly related to a user request). My intent was that it always be traceable. So the query string, which could contain secrets, is stripped off before it's stored in `TrackingContext.SubsystemId`. Any ideas for names?

TraceAddress, TraceableAddress, SafeAddress, TraceIdentifier, etc.?

**Comment by dlstucki** [comment]
Now released: https://github.com/Azure/azure-relay-dotnet/releases/tag/1.1.0-preview
