### ISSUE TITLE
Proxy property on HybridConnectionListener ignored

### ISSUE THREAD

**Issue by MarkOtter** [Azure/azure-relay-dotnet#82]
## Actual Behavior
When assigning the listener Proxy property with an instance of the WebProxy class, it is completely ignored when the same instance is used as WebRequest.DefaultProxy. It took us several hours of debugging and eventualy looking in the Azure Relay sources to figure this out.

It is not clear to us why this condition is present; isn't this a bug?
We believe [this condition ](https://github.com/Azure/azure-relay-dotnet/blob/dev/src/Microsoft.Azure.Relay/WebSockets/NetCore/WebSocketHandle.Managed.cs#L102)is the cause.

## Expected Behavior
Setting any instance of IWebProxy as the Proxy to the Listener causes it to be used, regardless of uses elsewhere.

## Versions  
- OS platform and version: Windows 10 Enterprise 1803 - 17134.345
- .NET Version: Core 2.1
- NuGet package version or commit ID: 2.0.0-preview1-20180523

**Comment by dlstucki** [comment]
@Priya91 Is there any reason the code checking for whether to use a proxy includes the check to ignore the proxy if it's WebRequest.DefaultWebProxy?

**Comment by MarkOtter** [comment]
@dlstucki, No we did not. Instead, we assigned a fresh new instance of `WebProxy` to the `Proxy` property. (This seemed to work with our local dev proxy, but not with the production proxy which is likely blocking the sb:// protocol, but that is another issue and we are looking into that)

Is the `UseBuiltInClientWebSocket` a more preferabele solution? If so, why? Are there side effects to consider with either approach?

**Comment by dlstucki** [comment]
WebRequest.DefaultProxy throws PlatformNotSupportedException if attempted to be used in .NET Core 2.0. That's most likely why that check is there at the [condition](https://github.com/Azure/azure-relay-dotnet/blob/dev/src/Microsoft.Azure.Relay/WebSockets/NetCore/WebSocketHandle.Managed.cs#L102) you pointed out.

This issue should be helped by the PR #108

**Comment by dlstucki** [comment]
If using netcoreapp2.1 or greater I think `UseBuiltInClientWebSocket = true` is the best way to go. However, it won't use the system configured property until the next release of this library (whatever comes after 2.0.0 Release).
