### ISSUE TITLE
Merge development to master

### ISSUE THREAD

**Issue by Gogeta094** [Azure/azure-relay-dotnet#88]
Good day!

Wondering if it's planned to merge development to master and release new version of Nuget?
We have issue in high load - HybridConnectionListener not responding to incoming Http requests.
I've tested this behaviour with dev build - and issue seems to be fixed.
Most likely it is fixed by this commit - https://github.com/Azure/azure-relay-dotnet/commit/87266eb1971b3f99cfe3b9f295cc746f8d727afe

Thanks!

**Comment by dlstucki** [comment]
https://github.com/Azure/azure-relay-dotnet/releases/tag/2.0.0
