### ISSUE TITLE
Looking for HCM (Hybrid Connection Manager) Source

### ISSUE THREAD

**Issue by masters3d** [Azure/azure-relay-dotnet#96]
Since BizTalk was discontinued last year. Is there a way to get the source code for HCM Hybrid Connection Manager? There is so much documentation around HCM but now that no new connections can be made using it, it would be nice to be able to deploy HCM using code. Is there some sample code for the manin HCM feature?

Related:
https://github.com/MicrosoftDocs/azure-docs/issues/26653

**Comment by dlstucki** [comment]
This is effectively the V2 of BizTalk Hybrid Connection Manager:
https://docs.microsoft.com/en-us/azure/app-service/app-service-hybrid-connections

**Comment by dlstucki** [comment]
Can you elaborate on which capability BizTalk HCM allowed which App Service Hybrid Connections does not?

**Comment by masters3d** [comment]
> Can you elaborate on which capability BizTalk HCM allowed that App Service Hybrid Connections does not?
From my understanding BizTalk allowed configuring a port on the actual relay connection that could then be `tunneled` then all that was needed on HCM was to provide that connection string and magic.   The portbridge is what I want but I need to set up the client to be an Azure Function or similar to replicate the same configuration. Thanks for the prompt response.  Very helpful.

**Comment by dlstucki** [comment]
Azure Functions also supports this "V2" Hybrid Connection Manager.
